# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "clippy"


[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--all-targets",
  "--all-features",
  "--color=always",
]
need_stdout = false

[keybindings]
c = "job:clippy"
